#!/usr/bin/env python

# Copyright (c) 2024 Platform9 systems. All rights reserved

# pylint: disable=too-many-locals

import logging
import sys
import os
import errno

from firkinize.database.mysqldb import MySqlDatabase

LOG_DIR = '/var/log/pf9/'

logging.basicConfig(level=logging.DEBUG)
LOG = logging.getLogger(__name__)

def mkdir_p(dir_path):

    """Create directories recursively."""
    try:
        os.makedirs(dir_path)
    except OSError as ex:
        if ex.errno != errno.EEXIST:
            raise

def configure_db():
    """
    Create the database, then add a user and grant permissions.
    """

    shortname = os.environ["SHORTNAME"]
    LOG.info('Creating database for customer %s', shortname)

    db_host = os.environ["DB_HOST"]
    db_port = os.environ["DB_PORT"]
    db_name = 'mors'

    mors_db_user = os.environ["MORS_DB_USER"]
    mors_db_password = os.environ["MORS_DB_PASSWORD"]

    admin_user = os.environ["DB_ROOT_USER"]
    admin_password = os.environ["DB_ROOT_PASSWORD"]

    db = MySqlDatabase(host=db_host, port=int(db_port), admin_user=admin_user, admin_pass=admin_password)

    db_created = db.check_create_db(db_name)
    if db_created:
        LOG.info("Database was created")

    grants_updated = db.check_add_grants(db_name, db_user=mors_db_user, db_pass=mors_db_password)
    if grants_updated:
        LOG.info("Grants were updated")

def main():

    mkdir_p(LOG_DIR)
    configure_db()

if __name__ == '__main__':
    sys.exit(main())
