[template]
src = 'pf9-mors.ini'
dest = '/etc/pf9/pf9-mors.ini'
owner = 'root'
mode = '0644'
keys = [
    '/region_id',
    '/services/mors/keystone/password',
    '/services/mors/db/password',
    '/services/mors/db/host',
]
